name: Build on Flutter Beta Commit

on:
  repository_dispatch:
    types: [flutter-beta-commit]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'beta'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build Web (or other platform)
        run: flutter build web # Or flutter build apk, flutter build ios, etc.

      # Add steps to deploy or publish your build artifacts if needed:
      # - name: Deploy to Firebase Hosting (example)
      #   uses: FirebaseExtended/action-hosting-deploy@v0
      #   with:
      #     repoToken: '${{ secrets.GITHUB_TOKEN }}'
      #     firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
      #     channelId: live
      #     projectId: your-firebase-project-id

      # - name: Upload build artifact (example)
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: web-build
      #     path: build/web