name: Check Dart Beta Updates

on:
  schedule:
    - cron: '0 1 * * *'  # Runs daily at 1 AM UTC (1 hour after Flutter workflow)
  workflow_dispatch:      # Allows manual trigger

# Add explicit permissions
permissions:
  contents: write      # This allows pushing to the repository
  pull-requests: read  # This is for reading PR information if needed

jobs:
  fetch-dart-beta-commits:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Create assets directory if it doesn't exist
        run: mkdir -p assets
        
      - name: Fetch Dart beta commits
        run: |
          # Fetch last 100 commits from Dart beta channel
          curl -H "Accept: application/vnd.github.v3+json" \
               -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               "https://api.github.com/repos/dart-lang/sdk/commits?sha=beta&per_page=100" \
               > assets/dart_beta_commits.json
          
      - name: Increment build number if changes exist
        run: |
          if ! git diff --quiet assets/dart_beta_commits.json; then
            # Read current version
            version_line=$(grep 'version:' pubspec.yaml)
            build_number=$(echo $version_line | cut -d'+' -f2)
            new_build=$((build_number + 1))
            
            # Update version in pubspec.yaml
            sed -i "s/version: [0-9]\+\.[0-9]\+\.[0-9]\++[0-9]\+/version: 1.0.3+$new_build/" pubspec.yaml
          fi
          
      - name: Commit and push if changes exist
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          git add assets/dart_beta_commits.json pubspec.yaml
          
          # Only commit and push if there are changes
          git diff --staged --quiet || (git commit -m "Update Dart beta commits and increment build number" && git push) 